import { Contract } from "ethers";

// Deployed contract addresses generated by your deployment step.
// This keeps the frontend working even when addresses change.
import Addresses from "../../../Addresses.json";

const REQUIRED_ENV = {
  userRegistry: "VITE_USER_REGISTRY_ADDRESS",
  chargingRequest: "VITE_CHARGING_REQUEST_ADDRESS",
  matchingContract: "VITE_MATCHING_CONTRACT_ADDRESS",
  energyValidation: "VITE_ENERGY_VALIDATION_ADDRESS",
  escrowPayment: "VITE_ESCROW_PAYMENT_ADDRESS",
};

function requireEnv(varName, fallback) {
  const value = import.meta.env[varName];
  if (value) return value;
  if (fallback) return fallback;
  throw new Error(`Missing ${varName} and no fallback address found.`);
}

const USER_REGISTRY_ABI = [
  "function admin() external view returns (address)",
  "function isvarifieduser(address _user) external view returns (bool)",
  "function getuser(address _user) external view returns (tuple(address wallet,string evmode,uint256 batterycapacity,bool isRegister,bool isvarified,uint8 role,uint256 reputation))",
  "function register_user(string memory model_ev,uint256 _battarycapacity,uint8 _role) external",
  "function varifyuser(address _user) external",
];

// Note: enum Status is OPEN=0, ACCEPTED=1, COMPLETED=2, CANCELED=3
const CHARGING_REQUEST_ABI = [
  "function requestCount() external view returns (uint256)",
  "function createrequest(uint256 energy_required,uint256 priceofenergyperkph,string location) external",
  "function getRequest(uint256 _id) external view returns (tuple(uint256 id,address reciever,uint256 energyrequired,uint256 priceperkilo,string location,uint8 status))",
  "function updatestatus(uint256 _id, uint8 _status) external",
];

const MATCHING_CONTRACT_ABI = [
  "function acceptrequest(uint256 _requestedid) external",
  "function getMatch(uint256 _requestId) external view returns (tuple(uint256 requestid,address reciever,address donor,bool active))",
];

const ENERGY_VALIDATION_ABI = [
  "function validator() external view returns (address)",
  "function started(uint256 _requestid) external",
  "function completed(uint256 _requestedid,uint256 _energydelivered) external",
  "function iscompleted(uint256 _requestedid) external view returns (bool)",
];

const ESCROW_PAYMENT_ABI = [
  "function admin() external view returns (address)",
  "function Escrowbalance(uint256) external view returns (uint256)",
  "function deposite(uint256 _requestedid) external payable",
  "function paymentrelease(uint256 _requestedid) external",
  "function paymentReleased(uint256 _requestedid) external view returns (bool)",
];

function getDefaultPricePerKilo() {
  const raw = import.meta.env.VITE_DEFAULT_PRICE_PER_KILO;
  if (!raw) return 1n;
  try {
    return BigInt(String(raw));
  } catch {
    return 1n;
  }
}

export function createChainContracts(signerOrProvider) {
  const userRegistryAddress = requireEnv(
    REQUIRED_ENV.userRegistry,
    Addresses.UserRegistry
  );
  const chargingRequestAddress = requireEnv(
    REQUIRED_ENV.chargingRequest,
    Addresses.ChargingRequest
  );
  const matchingContractAddress = requireEnv(
    REQUIRED_ENV.matchingContract,
    Addresses.MatchingContract
  );
  const energyValidationAddress = requireEnv(
    REQUIRED_ENV.energyValidation,
    Addresses.EnergyValidation
  );
  const escrowPaymentAddress = requireEnv(
    REQUIRED_ENV.escrowPayment,
    Addresses.EscrowPayment
  );

  return {
    userRegistry: new Contract(userRegistryAddress, USER_REGISTRY_ABI, signerOrProvider),
    chargingRequest: new Contract(chargingRequestAddress, CHARGING_REQUEST_ABI, signerOrProvider),
    matchingContract: new Contract(matchingContractAddress, MATCHING_CONTRACT_ABI, signerOrProvider),
    energyValidation: new Contract(energyValidationAddress, ENERGY_VALIDATION_ABI, signerOrProvider),
    escrowPayment: new Contract(escrowPaymentAddress, ESCROW_PAYMENT_ABI, signerOrProvider),
    defaultPricePerKilo: getDefaultPricePerKilo(),
  };
}

export const ChargingStatus = {
  OPEN: 0,
  ACCEPTED: 1,
  COMPLETED: 2,
  CANCELED: 3,
};

export function toWeiSafe(value) {
  // Helper if you need to convert numbers to BigInt strings safely.
  // (kept for future UI improvements)
  if (typeof value === "bigint") return value;
  if (typeof value === "number") return BigInt(Math.floor(value));
  return BigInt(String(value));
}
